export const actionTypes = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  GETALL_REQUEST: "TODOS_GETALL_REQUEST",
  GETALL_SUCCESS: "TODOS_GETALL_SUCCESS",
  GETALL_FAILURE: "TODOS_GETALL_FAILURE",

  DELETE_REQUEST: "TODOS_DELETE_REQUEST",
  DELETE_SUCCESS: "TODOS_DELETE_SUCCESS",
  DELETE_FAILURE: "TODOS_DELETE_FAILURE",
};
